# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor_assist.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14monitor_assist.proto\x12\nmeshtastic\"\\\n\x16MonitorAssistTelemetry\x12\x12\n\nheart_rate\x18\x01 \x01(\r\x12\x0b\n\x03lat\x18\x02 \x01(\x05\x12\x0b\n\x03lon\x18\x03 \x01(\x05\x12\x14\n\x0c\x61ssist_flags\x18\x04 \x01(\rBi\n\x14org.meshtastic.protoB\x13MonitorAssistProtosZ\"github.com/meshtastic/go/generated\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'monitor_assist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024org.meshtastic.protoB\023MonitorAssistProtosZ\"github.com/meshtastic/go/generated\252\002\024Meshtastic.Protobufs\272\002\000'
  _globals['_MONITORASSISTTELEMETRY']._serialized_start=36
  _globals['_MONITORASSISTTELEMETRY']._serialized_end=128
# @@protoc_insertion_point(module_scope)
